 
# Enter your validator's indexes, their ETH2 addresses (public keys)
# or the ETH1 addresses that you deposited from.
# You don't have to enter all of these, just remove (or comment out using #)
# the lines you don't need.
VALIDATOR_INDEXES:
  - 1
  - 2
  - 3
  - 4
  - 5

ETH2_ADDRESSES:
  - "0xa1d1ad0714035353258038e964ae9675dc0252ee22cea896825c01458e1807bfad2f9969338798548d9858a571f7425c"
  - "0xb2ff4716ed345b05dd1dfc6a5a9fa70856d8c75dcc9e881dd2f766d5f891326f0d10e96f3a444ce6c912b69c22c6754d"

ETH1_ADDRESSES:
  - "0xbef9124b9a1593982bb126bd97c1b8996caebade"
  - "0xdc69a0fc154b2ce0718e0eeaac041fdce455d72a"

START_DATE: "2020-12-01"
END_DATE: "2020-12-31"  # Inclusive

# Any CoinGecko-supported currency
CURRENCY: "EUR"

# Can be set to DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_LEVEL: "INFO"

BEACON_NODE:
  # Enter the hostname or IP address of the beacon node (e.g. localhost or 192.168.1.123)
  HOST: localhost
  # Enter the HTTP/RPC port of the beacon node
  # Defaults - Lighthouse 5052, Prysm 3500, Teku 5051, Nimbus 9190
  PORT: 5052
  # The amount of concurrent requests to make to the beacon node
  # (making more than 1 request at once makes things faster, but is
  # also more demanding on your beacon node)
  CONCURRENT_REQUESTS: 5

CSV:
  # Adds a line at the top of the file which contains the separator
  # used in the CSV file. This helps Excel import the data from
  # the CSV file.
  ADD_SEP_LINE: False
  # Specify the separator/delimiter to be used between each column
  DELIMITER: ";"
